
DROP TABLE TBL_TEST01;
DROP TABLE TBL_TEST02;
DROP TABLE TBL_TEST03;
DROP VIEW DUMMY_VIEW01;
DROP VIEW V_TEST01;
DROP MATERIALIZED VIEW MV_TEST01;
DROP MATERIALIZED VIEW MV_TEST02;
DROP TABLE TBL_TEST04;
DROP CLUSTER test_user.CLT_TEST01;
DROP TABLE DUMMY_TBL01;
DROP TABLE DUMMY_TBL01;
